//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.FluentMigrator.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Test.FluentMigrator.Test.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT [VersionInfo] ([Version], [AppliedOn]) VALUES (1, CAST(0x0000A10E00000000 AS DateTime)).
        /// </summary>
        internal static string script_data_test_migration_database_1_1 {
            get {
                return ResourceManager.GetString("script_data_test_migration_database_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT [VersionInfo] ([Version], [AppliedOn]) VALUES (1, CAST(0x0000A10E013D7DBC AS DateTime))
        ///INSERT [VersionInfo] ([Version], [AppliedOn]) VALUES (2, CAST(0x0000A10E013D7DBC AS DateTime))
        ///
        ///INSERT [TABLE] ([column01]) VALUES (&apos;Content before migration&apos;).
        /// </summary>
        internal static string script_data_test_migration_database_1_2 {
            get {
                return ResourceManager.GetString("script_data_test_migration_database_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT [VersionInfo] ([Version], [AppliedOn]) VALUES (1, CAST(0x0000A10E013D7DBC AS DateTime))
        ///INSERT [VersionInfo] ([Version], [AppliedOn]) VALUES (2, CAST(0x0000A10E013D7DBC AS DateTime))
        ///INSERT [VersionInfo] ([Version], [AppliedOn]) VALUES (3, CAST(0x0000A10E013D7DBC AS DateTime))
        ///INSERT [VersionInfo] ([Version], [AppliedOn]) VALUES (4, CAST(0x0000A10E013D7DBC AS DateTime))
        ///
        ///.
        /// </summary>
        internal static string script_data_test_migration_database_2_4 {
            get {
                return ResourceManager.GetString("script_data_test_migration_database_2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[code] [decimal](7, 3)
        ///)
        ///.
        /// </summary>
        internal static string script_schema_column_different_precision_database_a {
            get {
                return ResourceManager.GetString("script_schema_column_different_precision_database_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[code] [decimal](8, 3)
        ///)
        ///.
        /// </summary>
        internal static string script_schema_column_different_precision_database_b {
            get {
                return ResourceManager.GetString("script_schema_column_different_precision_database_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[code] [nvarchar](150)
        ///)
        ///.
        /// </summary>
        internal static string script_schema_column_different_size_database_a {
            get {
                return ResourceManager.GetString("script_schema_column_different_size_database_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[code] [nvarchar](50)
        ///)
        ///.
        /// </summary>
        internal static string script_schema_column_different_size_database_b {
            get {
                return ResourceManager.GetString("script_schema_column_different_size_database_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[code] [bigint]
        ///)
        ///.
        /// </summary>
        internal static string script_schema_column_different_type_database_a {
            get {
                return ResourceManager.GetString("script_schema_column_different_type_database_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[code] [nvarchar](50)
        ///)
        ///.
        /// </summary>
        internal static string script_schema_column_different_type_database_b {
            get {
                return ResourceManager.GetString("script_schema_column_different_type_database_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE1] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[column01] [nvarchar](50) NOT NULL
        ///)
        ///GO
        ///.
        /// </summary>
        internal static string script_schema_column_missing_datababse_tocompare_a {
            get {
                return ResourceManager.GetString("script_schema_column_missing_datababse_tocompare_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE1] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL
        ///)
        ///GO
        ///.
        /// </summary>
        internal static string script_schema_column_missing_datababse_tocompare_b {
            get {
                return ResourceManager.GetString("script_schema_column_missing_datababse_tocompare_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL
        ///)
        ///.
        /// </summary>
        internal static string script_schema_column_missing_database_a {
            get {
                return ResourceManager.GetString("script_schema_column_missing_database_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[column] [bigint]
        ///)
        ///.
        /// </summary>
        internal static string script_schema_column_missing_database_b {
            get {
                return ResourceManager.GetString("script_schema_column_missing_database_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE1](
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ///	[column01] [nvarchar](50) NOT NULL,
        ///	[column02] [nvarchar](50) NOT NULL
        ///)
        ///.
        /// </summary>
        internal static string script_schema_column_not_found_identity_database_a {
            get {
                return ResourceManager.GetString("script_schema_column_not_found_identity_database_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE1](
        ///	[id] [bigint] NOT NULL PRIMARY KEY,
        ///	[column01] [nvarchar](50) NOT NULL,
        ///	[column02] [nvarchar](50) NOT NULL
        ///)
        ///
        ///.
        /// </summary>
        internal static string script_schema_column_not_found_identity_database_b {
            get {
                return ResourceManager.GetString("script_schema_column_not_found_identity_database_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE1](
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ///	[column01] [nvarchar](50) NOT NULL,
        ///	[column02] [nvarchar](50) NOT NULL
        ///)
        ///GO
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE2](
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ///	[column01] [nvarchar](50) NOT NULL,
        ///	[column02] [nvarchar](50) NOT NULL,
        ///	[id_table1] [bigint] NOT NULL
        ///)
        ///GO
        ///CREATE NONCLUSTERED INDEX [IX_TABLE2_id_table1] ON [TABLE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string script_schema_column_not_included_indexe_database_a {
            get {
                return ResourceManager.GetString("script_schema_column_not_included_indexe_database_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE1](
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ///	[column01] [nvarchar](50) NOT NULL,
        ///	[column02] [nvarchar](50) NOT NULL
        ///)
        ///GO
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE2](
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ///	[column01] [nvarchar](50) NOT NULL,
        ///	[column02] [nvarchar](50) NOT NULL,
        ///	[id_table1] [bigint] NOT NULL
        ///)
        ///GO
        ///CREATE NONCLUSTERED INDEX [IX_TABLE2_id_table1] ON [TABLE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string script_schema_column_not_included_indexe_database_b {
            get {
                return ResourceManager.GetString("script_schema_column_not_included_indexe_database_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE](
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[column01] [nvarchar](50) NOT NULL,
        ///	[column02] [nvarchar](50) NOT NULL,
        ///	CONSTRAINT [UQ_TABLE] UNIQUE NONCLUSTERED ([column01] ASC)
        ///)
        ///GO.
        /// </summary>
        internal static string script_schema_column_not_included_unique_database_a {
            get {
                return ResourceManager.GetString("script_schema_column_not_included_unique_database_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE](
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[column01] [nvarchar](50) NOT NULL,
        ///	[column02] [nvarchar](50) NOT NULL,
        ///    CONSTRAINT [UQ_TABLE] UNIQUE NONCLUSTERED ([column01] ASC, [column02] ASC)
        ///)
        ///GO.
        /// </summary>
        internal static string script_schema_column_not_included_unique_database_b {
            get {
                return ResourceManager.GetString("script_schema_column_not_included_unique_database_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE] (
        ///	[id] [bigint]
        ///)
        ///.
        /// </summary>
        internal static string script_schema_column_nullable_database_a {
            get {
                return ResourceManager.GetString("script_schema_column_nullable_database_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE] (
        ///	[id] [bigint] NOT NULL
        ///)
        ///.
        /// </summary>
        internal static string script_schema_column_nullable_database_b {
            get {
                return ResourceManager.GetString("script_schema_column_nullable_database_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[code] [decimal](8, 2)
        ///)
        ///.
        /// </summary>
        internal static string script_schema_column_scale_notequal_database_a {
            get {
                return ResourceManager.GetString("script_schema_column_scale_notequal_database_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[code] [decimal](8, 3)
        ///)
        ///.
        /// </summary>
        internal static string script_schema_column_scale_notequal_database_b {
            get {
                return ResourceManager.GetString("script_schema_column_scale_notequal_database_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE](
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[column01] [nvarchar](50) NOT NULL
        ///)
        ///GO.
        /// </summary>
        internal static string script_schema_column_unique_database_a {
            get {
                return ResourceManager.GetString("script_schema_column_unique_database_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE](
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[column01] [nvarchar](50) NOT NULL,
        ///    CONSTRAINT [UQ_TABLE_column_01] UNIQUE NONCLUSTERED ([column01] ASC)
        ///)
        ///GO.
        /// </summary>
        internal static string script_schema_column_unique_database_b {
            get {
                return ResourceManager.GetString("script_schema_column_unique_database_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE](
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ///	[field01] [nvarchar](50) default &apos;Default&apos; NOT NULL,
        ///	[field02] [nvarchar](50) NOT NULL
        ///)
        ///GO
        ///.
        /// </summary>
        internal static string script_schema_column_value_default_database_a {
            get {
                return ResourceManager.GetString("script_schema_column_value_default_database_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE](
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ///	[field01] [nvarchar](50) NOT NULL,
        ///	[field02] [nvarchar](50) NOT NULL
        ///)
        ///GO
        ///.
        /// </summary>
        internal static string script_schema_column_value_default_database_b {
            get {
                return ResourceManager.GetString("script_schema_column_value_default_database_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE1](
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ///	[column01] [nvarchar](50) NOT NULL,
        ///	[column02] [nvarchar](50) NOT NULL
        ///)
        ///GO
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE2](
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ///	[column01] [nvarchar](50) NOT NULL,
        ///	[column02] [nvarchar](50) NOT NULL,
        ///	[id_table_1] [bigint] NOT NULL
        ///)
        ///ALTER TABLE [TABLE2]  WITH CHECK ADD  CONSTRAINT [FK_TABLE2_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string script_schema_foreign_key_database_a {
            get {
                return ResourceManager.GetString("script_schema_foreign_key_database_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE1](
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ///	[column01] [nvarchar](50) NOT NULL,
        ///	[column02] [nvarchar](50) NOT NULL
        ///)
        ///GO
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE2](
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ///	[column01] [nvarchar](50) NOT NULL,
        ///	[column02] [nvarchar](50) NOT NULL,
        ///	[id_table_1] [bigint] NOT NULL
        ///)
        ///ALTER TABLE [TABLE2]  WITH CHECK ADD  CONSTRAINT [FK_TABLE2_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string script_schema_foreign_key_database_b {
            get {
                return ResourceManager.GetString("script_schema_foreign_key_database_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE](
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ///	[column01] [nvarchar](50) NOT NULL,
        ///	[column02] [nvarchar](50) NOT NULL
        ///)
        ///GO
        ///.
        /// </summary>
        internal static string script_schema_indexe_database_a {
            get {
                return ResourceManager.GetString("script_schema_indexe_database_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE](
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ///	[column01] [nvarchar](50) NOT NULL,
        ///	[column02] [nvarchar](50) NOT NULL
        ///)
        ///GO
        ///CREATE NONCLUSTERED INDEX [IX_TABLE_column_01] ON [TABLE] (column01).
        /// </summary>
        internal static string script_schema_indexe_database_b {
            get {
                return ResourceManager.GetString("script_schema_indexe_database_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE1] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL
        ///)
        ///GO
        ///CREATE TABLE [TABLE2] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL
        ///)
        ///GO.
        /// </summary>
        internal static string script_schema_table_and_column_missing_a {
            get {
                return ResourceManager.GetString("script_schema_table_and_column_missing_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE1] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL
        ///)
        ///GO
        ///CREATE TABLE [TABLE2] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[column01] [nvarchar](50) NOT NULL
        ///)
        ///GO
        ///CREATE TABLE [TABLE3] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL
        ///)
        ///GO.
        /// </summary>
        internal static string script_schema_table_and_column_missing_b {
            get {
                return ResourceManager.GetString("script_schema_table_and_column_missing_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE1] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL
        ///)
        ///GO
        ///CREATE TABLE [TABLE2] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL
        ///)
        ///GO.
        /// </summary>
        internal static string script_schema_table_missing_database_a {
            get {
                return ResourceManager.GetString("script_schema_table_missing_database_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE dbo.[TABLE1] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL
        ///)
        ///GO
        ///CREATE TABLE dbo.[TABLE2] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL
        ///)
        ///GO
        ///CREATE TABLE dbo.[TABLE3] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL
        ///)
        ///GO.
        /// </summary>
        internal static string script_schema_table_missing_database_a_diferent_schema {
            get {
                return ResourceManager.GetString("script_schema_table_missing_database_a_diferent_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE1] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL
        ///)
        ///GO
        ///CREATE TABLE [TABLE2] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL
        ///)
        ///GO
        ///CREATE TABLE [TABLE3] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL
        ///)
        ///GO.
        /// </summary>
        internal static string script_schema_table_missing_database_b {
            get {
                return ResourceManager.GetString("script_schema_table_missing_database_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE SCHEMA schematest AUTHORIZATION dbo
        ///GO
        ///CREATE TABLE dbo.[TABLE1] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL
        ///)
        ///GO
        ///CREATE TABLE dbo.[TABLE2] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL
        ///)
        ///GO
        ///CREATE TABLE schematest.[TABLE3] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL
        ///)
        ///GO.
        /// </summary>
        internal static string script_schema_table_missing_database_b_diferent_schema {
            get {
                return ResourceManager.GetString("script_schema_table_missing_database_b_diferent_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE1] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL
        ///)
        ///GO
        ///CREATE TABLE [TABLE2] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL
        ///)
        ///GO.
        /// </summary>
        internal static string script_schema_table_missing_database_tocompare_a {
            get {
                return ResourceManager.GetString("script_schema_table_missing_database_tocompare_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE1] (
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL
        ///)
        ///GO
        ///.
        /// </summary>
        internal static string script_schema_table_missing_database_tocompare_b {
            get {
                return ResourceManager.GetString("script_schema_table_missing_database_tocompare_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///CREATE TABLE [dbo].[VersionInfo](
        ///	[Version] [bigint] NOT NULL,
        ///	[AppliedOn] [datetime] NULL,
        ///	[Description] [nvarchar](1024) NULL
        ///) ON [PRIMARY]
        ///
        ///GO
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE](
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[column01] [nvarchar](255) NOT NULL,
        ///	[column02] [nvarchar](255) NULL,
        ///	[columnInt] [int] NULL,
        ///	[column_date] [datetime] NULL,
        ///	[id_TABLE_origin] [bigint] NULL,
        /// CONSTRAINT  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string script_schema_test_migration_database_1_0 {
            get {
                return ResourceManager.GetString("script_schema_test_migration_database_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///CREATE TABLE [dbo].[VersionInfo](
        ///	[Version] [bigint] NOT NULL,
        ///	[AppliedOn] [datetime] NULL,
        ///	[Description] [nvarchar](1024) NULL
        ///) ON [PRIMARY]
        ///GO
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE](
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[column01] [nvarchar](50) NOT NULL,
        ///	[column02] [int] NULL,
        ///	[column_integer] [int] NULL,
        ///	[id_TABLE_origin] [bigint] NULL,
        /// CONSTRAINT [PK__TABLE__3213E83F48CFD27E] PRIMARY KEY [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string script_schema_test_migration_database_1_1 {
            get {
                return ResourceManager.GetString("script_schema_test_migration_database_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///CREATE TABLE [dbo].[VersionInfo](
        ///	[Version] [bigint] NOT NULL,
        ///	[AppliedOn] [datetime] NULL,
        ///	[Description] [nvarchar](1024) NULL
        ///) ON [PRIMARY]
        ///GO
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE2](
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[column] [nvarchar](255) NOT NULL,
        /// CONSTRAINT [PK_TABLE2] PRIMARY KEY CLUSTERED 
        ///(
        ///	[id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string script_schema_test_migration_database_1_2 {
            get {
                return ResourceManager.GetString("script_schema_test_migration_database_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///CREATE TABLE [dbo].[VersionInfo](
        ///	[Version] [bigint] NOT NULL,
        ///	[AppliedOn] [datetime] NULL,
        ///	[Description] [nvarchar](1024) NULL
        ///) ON [PRIMARY]
        ///GO
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE2](
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[column] [nvarchar](255) NOT NULL,
        /// CONSTRAINT [PK_TABLE2] PRIMARY KEY CLUSTERED 
        ///(
        ///	[id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string script_schema_test_migration_database_2_3 {
            get {
                return ResourceManager.GetString("script_schema_test_migration_database_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///CREATE TABLE [dbo].[VersionInfo](
        ///	[Version] [bigint] NOT NULL,
        ///	[AppliedOn] [datetime] NULL,
        ///	[Description] [nvarchar](1024) NULL
        ///) ON [PRIMARY]
        ///GO
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE2](
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[column] [nvarchar](255) NOT NULL,
        /// CONSTRAINT [PK_TABLE2] PRIMARY KEY CLUSTERED 
        ///(
        ///	[id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string script_schema_test_migration_database_2_4 {
            get {
                return ResourceManager.GetString("script_schema_test_migration_database_2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE](
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ///	[column01] [nvarchar](50) NOT NULL,
        ///	[column02] [nvarchar](50) NOT NULL
        ///)
        ///GO
        ///CREATE TRIGGER [dbo].[table_trigger] ON [dbo].[TABLE] FOR INSERT AS
        ///begin
        ///	select 1 
        ///end.
        /// </summary>
        internal static string script_schema_trigger_database_a {
            get {
                return ResourceManager.GetString("script_schema_trigger_database_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [TABLE](
        ///	[id] [bigint] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ///	[column01] [nvarchar](50) NOT NULL,
        ///	[column02] [nvarchar](50) NOT NULL
        ///)
        ///GO
        ///.
        /// </summary>
        internal static string script_schema_trigger_database_b {
            get {
                return ResourceManager.GetString("script_schema_trigger_database_b", resourceCulture);
            }
        }
    }
}
